# Generated by Django 4.2.1 on 2023-06-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Category',
            new_name='category',
        ),
    ]
